chore(scripts/wasm): re-encode binaries with mvp-ish call_indirect tables
One of the great side effects of supporting so many browser versions is
that you get to run into problems that nobody else really has to deal
with, and today's example is again dealing with compilers.

TL;DR: Chrome before version 100 rejects the WebAssembly that current
rustc emits with an error like this:

> CompileError: WebAssembly.compile(): Compiling function
> #4:\"_RINvMs0_NtNtNtNtCsdl5sGgnNXvY_3std3sys4sync4on...\" failed:
> expected table index 0, found 128 @+664

The root cause of this is that my "baseline" build isn't actually a
baseline build, it was just a default rustc build minus simd128 support.
rustc's default wasm feature set for wasm32-unknown-unknown is roughly:

- bulk-memory (Chrome 75)
- multivalue (Chrome 85)
- mutable-globals (Chrome 74)
- nontrapping-fptoint (Chrome 75)
- reference-types (Chrome 96)
- sign-ext (Chrome 74)

The big blocker is reference-types, which makes LLVM encode
call_indirect table indicies as a relocatable LEB128 entry instead of
the MVP's single reserved null byte. The table index is zero, Chrome 75
reads one byte, sees 0x80, and throws an error.

Extra fun, this was failing in a function in rust's standard library and
we really don't want to make people use the nightly rust compiler so
that we can recompile the rust stdlib without these features.

So instead we prune away the features using wasm-opt to strip them away
like unwanted paint.

This should give us Chrome 75 support.

Signed-off-by: Xe Iaso <me@xeiaso.net>